# k8s/2-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: default
type: Opaque
stringData:
  # Remplacer par vos vraies clés
  OPENAI_API_KEY: "sk-votre-cle-openai"
  GROQ_API_KEY: "gsk-votre-cle-groq"